### ISSUE TITLE
Shape draw operations

### ISSUE THREAD

**Issue by tristen** [mapbox/gl-draw#11]
- [x] Click and dragging should draw a shape with variable width+height
- [ ] Click and dragging with the __alt key__ should draw a shape with fixed width+height with center pinning (i.e. the drawn layer expands in size across the canvas in both directions)
- [ ] Click and dragging with the __shift key__ should draw a shape with fixed width+height with top-left  pinning.

**Comment by tmcw** [comment]
Closing: current behavior is enough.
