### ISSUE TITLE
Undo/Redo management

### ISSUE THREAD

**Issue by tristen** [mapbox/gl-draw#14]
Should be built into the editor with Immutable.js wrapped into the current [store](https://github.com/mapbox/gl-draw/blob/dev-pages/src/store.js). Some @tmcw reading material on the subject:

http://www.macwright.org/2015/05/18/practical-undo.html

As a UI I like the pattern used in [inbox](inbox.google.com) 

![screen shot 2015-06-12 at 10 26 17 am](https://cloud.githubusercontent.com/assets/61150/8132221/1dec4c3c-10ee-11e5-99c0-6fccff7619c1.png)

**Comment by kelvinabrokwa** [comment]
The structure of the stores changed quite a bit in https://github.com/mapbox/gl-draw/pull/83 so undo redo has been removed for now. It will be readded as a part of another PR.
