### ISSUE TITLE
PRELAUNCH: Tests

### ISSUE THREAD

**Issue by tristen** [mapbox/gl-draw#17]
Set up the framing for this in https://github.com/mapbox/gl-draw/commit/a53d849378877b020022ec79defa4580f4bda462 might try using https://github.com/azer/prova instead of smokestack.

**Comment by tmcw** [comment]
This should be tested after the basic featureset is complete.

**Comment by kelvinabrokwa** [comment]
this is being tracked here -> https://github.com/mapbox/gl-draw/issues/48
