### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by tristen** [mapbox/gl-draw#18]
- Description
  - Overview
  - Version number
  - Testing badges
  - Link to live site (if applicable)
- Usage
  - How to use it with code samples
  - Links to documentation (if applicable)
- Running locally
  - How to run it locally
  - Include dependencies
- Testing
  - How to test it locally

**Comment by tmcw** [comment]
Closing: readme is good enough.

**Comment by tristen** [comment]
It is! Thanks to @jakepruitt
