### ISSUE TITLE
Use prefix

### ISSUE THREAD

**Issue by tmcw** [mapbox/gl-draw#20]
The prefix module https://www.npmjs.com/package/prefix is a robust replacement for [the prefix detection in this module](https://github.com/mapbox/gl-draw/blob/39ac8f3986427f36a94b6ac8ddedf3844fb63346/src/util.js#L73-L84)

**Comment by tristen** [comment]
Punt here too? https://github.com/mapbox/mapbox-gl-js/issues/1294#issuecomment-113222812

**Comment by tristen** [comment]
Let's punt - If prefixing scales out to more properties we should switch.
