### ISSUE TITLE
Remove store & undo/redo

### ISSUE THREAD

**Issue by tmcw** [mapbox/gl-draw#21]
I think that gl-draw should, at its core, only emit events. Undo/redo should be implemented outside of core.

**Comment by tristen** [comment]
cc @jfirebaugh as he had some thoughts on this. Originally I didn't have undo/redo management. I'd argue we still need store for object management. Let's build something that can be used as a plugin very well and not require a ton from the implementor

**Comment by tmcw** [comment]
The hard part of building this is **getting drawing interactions right**. That is certified difficult.

The easy part is undo/redo. I guarantee that once the hard part is done, we can build a very nice API on top of it and make it very easy for implementors. That should come after the hard part is done.

**Comment by tristen** [comment]
But store management is already in place and benefits draw interactions.

**Comment by tmcw** [comment]
It distracts from the unfinished core functionality of this module.

**Comment by tristen** [comment]
How exactly?? Keeping a state of the data around to put a feature in edit mode or plot edit nodes is extremely helpful.

**Comment by tmcw** [comment]
Right now this is a drawing interface that cannot drag a marker but has a full-fledged immutable undo/redo data store.

**Comment by tmcw** [comment]
Let's leave this for now.
