### ISSUE TITLE
Drawing puts markers in the wrong place

### ISSUE THREAD

**Issue by tmcw** [mapbox/gl-draw#29]
![draw_marker](https://cloud.githubusercontent.com/assets/32314/8737608/e4f27d2e-2bf1-11e5-81fb-54891039bb0c.gif)

**Comment by kelvinabrokwa** [comment]
![point](https://cloud.githubusercontent.com/assets/7795202/8785387/611eea6c-2ef5-11e5-9fdf-c306b686c1a0.gif)
