### ISSUE TITLE
Guide line is not centered in vertex circle

### ISSUE THREAD

**Issue by tmcw** [mapbox/gl-draw#30]
<img width="321" alt="2015-07-16 at 7 36 pm" src="https://cloud.githubusercontent.com/assets/32314/8737615/00768c98-2bf2-11e5-8ff1-565df8d9058c.png">

The guide lines are starting from closer to the bottom than to the top.

**Comment by kelvinabrokwa** [comment]
done in https://github.com/mapbox/gl-draw/pull/40
