### ISSUE TITLE
Add button for feature delete

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/gl-draw#35]
Is this necessary in addition to the keyboard shortcut?

**Comment by kelvinabrokwa** [comment]
Kelvin thinks yes

**Comment by tristen** [comment]
So it might be necessary for a button like this to exist for mobile.

I wouldn't want this to operate at all the way it's done in Leaflet-draw where you click individual features to delete them when the trash icon is selected. I'm sort of seeing this as an icon that appears in the toolbar when a feature(s) is selected the the state of the editor is in edit mode. When the trash icon is pressed the feature(s) are immediately deleted.

**Comment by kelvinabrokwa** [comment]
> I'm sort of seeing this as an icon that appears in the toolbar when a feature(s) is selected the the state of the editor is in edit mode. When the trash icon is pressed the feature(s) are immediately deleted.

yup, its already implemented like this -> https://github.com/mapbox/gl-draw/blob/dev-pages/src/draw.js#L164-L169 and https://github.com/mapbox/gl-draw/blob/dev-pages/src/draw.js#L173

**Comment by kelvinabrokwa** [comment]
- [ ] Create icon
- [ ] Implement functionality
