### ISSUE TITLE
Use mapbox gl instead of homegrown setoptions

### ISSUE THREAD

**Issue by tmcw** [mapbox/gl-draw#37]
https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/util.js#L327-L345

This is exported by mapbox gl - we should use this instead of homegrowing setOptions

**Comment by kelvinabrokwa** [comment]
is it? https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/util.js#L335

**Comment by tmcw** [comment]
it's not publicly documented, but it's exported under mapboxgl.util

**Comment by kelvinabrokwa** [comment]
:+1: -> https://github.com/mapbox/gl-draw/commit/f56048bdee079bb6425eca0c7a6d7810a2dd7b1b

**Comment by jfirebaugh** [comment]
Please don't do this. If it's explicitly marked as a private API, it's just that -- not meant to be used by other libraries, could be removed or changed at any time.
