### ISSUE TITLE
Simplification of midpoint calculation breaks down at large scales

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/gl-draw#55]
The average is cheap but it just won't cut it -> https://github.com/mapbox/gl-draw/blob/dev-pages/src/edit_store.js#L85

![](https://cloud.githubusercontent.com/assets/7795202/8948354/5f6eb64a-3574-11e5-905b-bbae44b1537b.png)

**Comment by tmcw** [comment]
_projections_

Solution is usually to map.project points to pixel space, find the midpoint, and then project it back.

**Comment by kelvinabrokwa** [comment]
@tmcw I'm just going to go ahead and heed your warning and stop worrying about perf while I'm still implementing core functionality...

**Comment by tmcw** [comment]
projection should be super fast, it's super simple to do foward/reverse proj in webmercator - on the order of 2-3 sin/tan calls
