### ISSUE TITLE
Devlog

### ISSUE THREAD

**Issue by tmcw** [mapbox/gl-draw#82]
@kelvinabrokwa is writing a killer devlog about gl-draw and publishing it on /hey on October 12, Columbus Day

**Comment by lbud** [comment]
I can't wait to read this devlog @kelvinabrokwa

**Comment by lbud** [comment]
on October 12

**Comment by kelvinabrokwa** [comment]
@lbud this is going to be the most :fire: devlog /hey has ever seen. Brace yo'selves.

**Comment by karenzshea** [comment]
![unpaid_intern](https://cloud.githubusercontent.com/assets/5521326/10236273/aba4959a-6871-11e5-914a-388fee397bc3.gif)

@kelvinabrokwa no pressure but really lookin forward to the sickness you're about to unleash on us

**Comment by mtirwin** [comment]
One good Life Aquatic intern gif deserves another.

![](http://i.giphy.com/TC4dOmxbrznlm.gif)

**Comment by kelvinabrokwa** [comment]
it has been dropped -> https://github.com/mapbox/hey/issues/4911
